name 'worker_standard'
description 'Auto-generated Role for worker_standard'
default_attributes('rvm' =>   { 'default' => '1.9.3-p547',
                                'rubies' => [{ 'name' => '1.9.3-p547' }],
                                'gems' => %w(bundler rake) },
                   'golang' =>   { 'multi' =>     { 'versions' => ['go1.3'], 'aliases' => [], 'default_version' => 'go1.3' } },
                   'travis_build_environment' => { 'use_tmpfs_for_builds' => false }
)
run_list('recipe[travis_build_environment]',
         'recipe[apt]',
         'recipe[build-essential]',
         'recipe[clang::tarball]',
         'recipe[golang::multi]',
         'recipe[networking_basic]',
         'recipe[openssl]',
         'recipe[sysctl]',
         'recipe[git::ppa]',
         'recipe[mercurial]',
         'recipe[bazaar]',
         'recipe[subversion]',
         'recipe[scons]',
         'recipe[unarchivers]',
         'recipe[md5deep]',
         'recipe[dictionaries]',
         'recipe[libqt4]',
         'recipe[libgdbm]',
         'recipe[libncurses]',
         'recipe[libossp-uuid]',
         'recipe[libffi]',
         'recipe[ragel]',
         'recipe[imagemagick]',
         'recipe[mingw32]',
         'recipe[libevent]',
         'recipe[java]',
         'recipe[ant]',
         'recipe[maven]',
         'recipe[sqlite]',
         'recipe[rvm]',
         'recipe[rvm::multi]',
         'recipe[python]',
         'recipe[python::devshm]',
         'recipe[python::pip]',
         'recipe[nodejs::multi]',
         'recipe[mysql::server_on_ramfs]',
         'recipe[postgresql]',
         'recipe[redis]',
         'recipe[riak]',
         'recipe[mongodb]',
         'recipe[couchdb::ppa]',
         'recipe[memcached]',
         'recipe[neo4j-server::tarball]',
         'recipe[cassandra::tarball]',
         'recipe[rabbitmq::with_management_plugin]',
         'recipe[zeromq::ppa]',
         'recipe[elasticsearch]',
         'recipe[sphinx::all]',
         'recipe[xserver]',
         'recipe[firefox::tarball]',
         'recipe[chromium]',
         'recipe[phantomjs::tarball]',
         'recipe[emacs::nox]',
         'recipe[vim]',
         'recipe[sweeper]')
